export default () => [
    '批量新增代理制品白名单',
    'API: PUT /api/remote/whitelist/batch/',
    `HOST: ${location.origin}/repository`,
    'API 名称: insert_remote_package_whitelist_batch',
    '',
    '功能说明：',
    '中文：批量新增代理制品白名单',
    'English：batch create remote package whitelist',
    '',
    '请求体',
    '[',
    '     {',
    '         "packageKey":"conm.alibaba:fastjson",',
    '        "versions":["1.0","2.0"],',
    '        "type":"MAVEN"',
    '    },',
    '    {',
    '         "packageKey":"net.canway:bkrepo",',
    '        "versions":["1.1","2.2],',
    '        "type":"MAVEN"',
    '    }',
    ']',
    '请求字段说明',
    'packageKey | String       | 默认无 | 必传   | 唯一包名(不同仓库类型有不同校验规则，参考文档声明) | package key',
    'versions   | List<String> | 默认无 | 非必传 | 新增的白名单版本                                | versions',
    'type       | String       | 默认无 | 必传   | 仓库类型                                       | repository type',
    '',
    '响应体',
    '{',
    '     "code": 0,',
    '    "message": null,',
    '    "data": 2,',
    '    "traceId": ""',
    '}',
    'data字段说明',
    'data | Int | 批量操作成功数统计 | batch insert success count'
]
