spring:
  application:
    name: ${service.name}
    desc: Replication Service
  cloud:
    stream:
      function:
        definition: artifactEvent
      bindings:
        artifactEvent-in-0:
          group: replication
          destination: artifactEvent
          binder: __BK_REPO_STREAM_BINDER__
        artifactEvent-out-0:
          destination: artifactEvent
          binder: __BK_REPO_STREAM_BINDER__
server:
  port: __BK_REPO_REPLICATION_PORT__
logging:
  path: ${logging.path-common}/${service.name}
service:
  name: replication
replication:
  domain: ${cluster.self.url}/replication
