spring:
  application:
    name: ${service.name}
    desc: Docker Service
  cloud:
    stream:
      function:
        definition: artifactEvent
      bindings:
        artifactEvent-in-0:
          group: docker
          destination: artifactEvent
          binder: pulsar
server:
  port: __BK_REPO_DOCKER_PORT__
auth:
  enable: true
  # auth.url为空时, 根据docker.domain和Host请求头生成
  url:
logging:
  level:
    com.tencent.bkrepo.docker: DEBUG
  path: ${logging.path-common}/${service.name}
docker:
  domain: __BK_REPO_DOCKER_DOMAIN__

service:
  name: docker
