spring:
  application:
    name: ${service.name}
    desc: Scanner Service
  # 上报的扫描结果比较大的时候需要配置
  servlet:
    multipart:
      max-request-size: 100MB
  cloud:
    stream:
      function:
        definition: artifactEvent
      bindings:
        artifactEvent-in-0:
          group: scanner
          destination: artifactEvent
          binder: pulsar
server:
  port: __BK_REPO_SCANNER_PORT__
logging:
  path: ${logging.path-common}/${service.name}
service:
  name: scanner

scanner:
  # 默认项目扫描子任务数量限制
  defaultProjectSubScanTaskCountLimit: 20
  # 用于生成扫描报告路径
  detailReportUrl: http://localhost