spring:
  application:
    name: ${service.prefix}${service.name}${service.suffix}
    desc: Maven Service
server:
  port: __BK_REPO_MAVEN_PORT__
logging:
  path: ${logging.path-common}/${service.name}
service:
  name: maven
maven:
  domain: ${cluster.self.url}/maven
