# Common config Template 重复的通用的配置抽离在到

spring:
  profiles:
    active: __BK_REPO_PROFILES_ACTIVE__
  application:
    version: 4.0.0
  cloud:
    consul:
      discovery:
        tags: __DEVOPS_CONSUL_TAG__
        health-check-path: /management/health
        heartbeat:
          enabled: true
        query-passing: true
        preferIpAddress: true
      port: __DEVOPS_CONSUL_PORT__
    stream:
      binders:
        noop:
          type: noop
        file:
          type: file
        pulsar:
          type: pulsar
          environment:
            spring:
              pulsar:
                # Comma delimited list of ip:port pairs
                serviceUrl: __BK_REPO_PULSAR_SERVICE_URL__
                tokenAuthValue: __BK_REPO_PULSAR_AUTH_JWT_TOKEN__
                tenant: __BK_REPO_PULSAR_TENANT__
                namespace: __BK_REPO_PULSAR_NAMESPACE__
      function:
        autodetect: false
      default-binder: noop
  data:
    mongodb:
      socket-keep-alive: true
      max-connection-idle-time: 60000
      autoConnectRetry: true
      socketTimeout: 1500
      ### 单机情况下关闭事务，否则报错
      transaction:
        enabled: false
      uri: mongodb://__BK_REPO_MONGODB_USER__:__BK_REPO_MONGODB_PASSWORD__@__BK_REPO_MONGODB_ADDR__/__BK_REPO_MONGODB_DB_NAME__?maxPoolSize=50&replicaSet=rs0
  redis:
    host: __BK_CI_REDIS_HOST__
    port: __BK_CI_REDIS_PORT__
    password: __BK_CI_REDIS_PASSWORD__
    timeout: 900
    # Redis sentinel 集群方式配置
    sentinel:
      # name of the master node
      master: __BK_CI_REDIS_SENTINEL_MASTER_NAME__
      # Comma delimited list of master_ip:port pairs
      nodes: __BK_CI_REDIS_SENTINEL_ADDR__
      password: __BK_CI_REDIS_SENTINEL_PASSWORD__

feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 600000
        readTimeout: 600000
        logger-level: basic
  compression:
    request:
      enabled: true
    response:
      enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          semaphore:
            maxConcurrentRequests: 100
          thread:
            timeoutInMilliseconds: 600000

ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 30000

logging:
  config: classpath:logback-config.xml
  path-common: __BK_HOME__/logs/bkrepo

storage:
  type: __BK_REPO_STORAGE_TYPE__
  filesystem:
    path: __BK_CI_DATA_SHARE_DIR__/repo/filesystem/store
    cache:
      enabled: false
      path: __BK_CI_DATA_SHARE_DIR__/repo/filesystem/cached
      expireDays: 12
  s3:
    endpoint: __BK_REPO_S3_STORAGE_ENDPOINT__
    bucket: __BK_REPO_S3_STORAGE_BUCKET__
    accessKey: __BK_REPO_S3_STORAGE_ACCESS_KEY__
    secretKey: __BK_REPO_S3_STORAGE_SECRET_KEY__
    region: __BK_REPO_S3_STORAGE_REGION__

security:
  # HTTP认证相关配置
  auth:
    # 默认开启
    enabled: true
    # jwt认证相关配置
    jwt:
      # 默认值
      secretKey: secret@key
      # spring Duration配置格式，可以带时间单位，为0表示永不过期，默认为0
      expiration: 0
    # 平台个人令牌认证
    devopsToken:
      enabled: true
  crypto:
    rsaAlgorithm: RSA/ECB/PKCS1Padding
    privateKeyStr: "MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAMaoDhrj
                      +Da2tGpawrE8et6vHBjprVj0UiCEza7JVymYTo9gd/pxNJRnbf6NehUL1WP8D6f5e2XZEDNfqXOqyEjPqOKtWIYI6ZLQeQIuAXgyGE5aP3
                      /KVHFnxk+IuzcJtvqTAthfeuVXGel9ATP8hlEyDuCJe7/orBjIVYFk3p+PAgMBAAECgYAGYwLJFIk3YRpdzPszbYlZvXF
                      +z4x2LqyxRPPD6c82lCH6dBSHZbpWBxk/NNc29AFxTHpIYTn5ZUgjDrFI+bWkqxvgqWS/oyfB6rxajIQjTeorsGvt
                      /oumxQA7hvUE2XXLi218RXCURWgz/FZnvNhGhPYUOJWHoPeNlVx3V5mG8QJBAOzP9iSPcw1YJkv6uAgY4MRv1GqPu3NcMif
                      +DQVPOZCNPq7ynSg15Zl3HMpl6jAZNJ/AUXRby3tLhO8WiWr6C8cCQQDWwKbhy4AZ5SDigFIPtk
                      /655Uzprm2JaZSvGkBeOSB9EYCUC1ApKeImrufPZpSj3Ood/fbMyA6cl8Bswl2z335AkBTNa
                      +ToSQYKEUspWhM0BEKdRD6cI65NkgZbVc96lybwkWoS2+VVXrbtdLT+4OSawjmqTj13dtd82c
                      +a3jVsg65AkEAn1kiO0caDZzj8s2OlpQL8rwmDMZ45Lw5FwkwzWPcAsWzsQG3IlFK8uUFtRoryXkiM
                      +6Y3nCoSFYXQxaLPjqmWQJBAI2tn28XAHFcSd0UnS8L6exJuMdjCw4huI5
                      FOeZ0arf5NrWDFoKU30Crw2ozmRBcDvtjDVH9sn8oLC2ObCFItlM="
    publicKeyStr: "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDGqA4a4
                      /g2trRqWsKxPHrerxwY6a1Y9FIghM2uyVcpmE6PYHf6cTSUZ23+jXoVC9Vj/A+n+Xtl2RAzX6lzqshIz6jirViGCOmS0HkCLgF4MhhOWj9
                      /ylRxZ8ZPiLs3Cbb6kwLYX3rlVxnpfQEz/IZRMg7giXu/6KwYyFWBZN6fjwIDAQAB"
  # 微服务认证相关配置
  service:
    # 默认开始
    enabled: false
    # 默认值
    secretKey: secret@key
  anonymous:
    interceptor:
      enabled: __BK_REPO_ANONYMOUS_ACCESS_INTERCEPTOR_ENABLED__
      cidr:
        whiteList: __BK_REPO_ANONYMOUS_ACCESS_CIDR_WHITELIST__
service:
  suffix: "__BK_REPO_SERVICE_SUFFIX__"
  prefix: "__BK_REPO_SERVICE_PREFIX__"
  devops-prefix: "__BK_DEVOPS_SERVICE_PREFIX__"

# 许可需要的配置  
service-suffix: "__BK_REPO_LICENSE_SUFFIX__"

# 自身节点信息配置
cluster:
  self:
    name: __BK_REPO_CLUSTER_SELF_NAME__
    url: __BK_HTTP_SCHEMA__://__BK_REPO_CLUSTER_SELF_DOMAIN__
    username: __BK_REPO_CLUSTER_SELF_USERNAME__
    password: __BK_REPO_CLUSTER_SELF_PASSWORD__
  role: __BK_REPO_ROLE_TYPE__
  center:
    name: __BK_REPO_CLUSTER_CENTER_NAME__
    url: __BK_HTTP_SCHEMA__://__BK_REPO_CLUSTER_CENTER_DOMAIN__
    username: __BK_REPO_CLUSTER_CENTER_USERNAME__
    password: __BK_REPO_CLUSTER_CENTER_PASSWORD__

bk:
  ci:
    # license使用的域名
    domain: __BK_DOMAIN__
  paas:
    host: __BK_PAAS_PUBLIC_URL__
    version: "__BK_PAAS_VERSION__"

esb:
  code: __BK_CI_APP_CODE__
  secret: __BK_CI_APP_TOKEN__

# 需要限制许可人数的时候
devopsGateway:
  host: __BK_CI_PUBLIC_URL__

# canway certificate
license:
  auth:
    host: __BK_HTTP_SCHEMA__://__CW_LICENSE_HOST__:__CW_LICENSE_PORT__

# cpack 对外服务域名
cpack:
  host: __BK_HTTP_SCHEMA__://__BK_REPO_FQDN__
  
devops:
  bkHost: __BK_HTTP_SCHEMA__://__BK_PAAS_FQDN__
  appCode: __APP_CODE__
  appSecret: __APP_TOKEN__
  devopsHost: __BK_HTTP_SCHEMA__://__BK_CI_FQDN__

# CI集成模式固定该配置
auth:
  realm: canway
# CI集成模式消息通知
mail:
  mailNotifyType: devops

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

view:
  domain: __BK_HTTP_SCHEMA__://__BK_REPO_FQDN__
