spring:
  application:
    name: ${service.prefix}${service.name}${service.suffix}
    desc: Scanner Service
server:
  port: __BK_REPO_SCANNER_PORT__
logging:
  path: ${logging.path-common}/${service.name}
service:
  name: scanner

# 用于存储详细扫描报告
scanner:
  spring:
    data:
      mongodb:
        uri: __BK_REPO_SCANNER_MONGODB_URI__
        transaction:
          enabled: false
