spring:
  application:
    name: ${service.name}
    desc: Docker Service
  cloud:
    stream:
      function:
        definition: artifactEvent
      bindings:
        artifactEvent-in-0:
          group: docker
          destination: artifactEvent
          binder: __BK_REPO_STREAM_BINDER__
server:
  port: __BK_REPO_DOCKER_PORT__
auth:
  enable: true
  # url为空时, 根据docker.domain、auth.scheme以及Host请求头生成; 不为空时忽略scheme的值
  url:
  # 仅在url为空时有效, https之外的其它值都认为是http, 无该配置项时从请求信息获取scheme
  scheme: __BK_HTTP_SCHEMA__
logging:
  level:
    com.tencent.bkrepo.docker: DEBUG
  path: ${logging.path-common}/${service.name}
docker:
  domain: __BK_REPO_DOCKER_DOMAIN__

service:
  name: docker
