spring:
  application:
    name: ${service.name}
    desc: Cocoapods Service
server:
  port: __BK_REPO_COCOAPODS_PORT__
logging:
  path: ${logging.path-common}/${service.name}
service:
  name: cocoapods
cocoapods:
  domain: ${cluster.self.url}/cocoapods
