spring:
  application:
    name: ${service.prefix}${service.name}${service.suffix}
    desc: Replication Service
  cloud:
    stream:
      bindings:
        artifactEvent-in-0:
          destination: artifact-event
          group: replication
        artifactEvent-out-0:
          destination: artifact-event
      function:
        definition: artifactEvent
      binders:
        file:
          type: file
        memory:
          type: memory
      file:
        default:
          path: /data/bkee/repo/streams
      memory:
        default:
          queue-size: 2048
          worker-pool-size: 1
      default-binder: file
server:
  port: __BK_REPO_REPLICATION_PORT__
logging:
  path: ${logging.path-common}/${service.name}
service:
  name: replication
replication:
  domain: ${cluster.self.url}/replication
