spring:
  application:
    name: ${service.name}
    desc: Job Service
server:
  port: __BK_REPO_JOB_PORT__
logging:
  path: ${logging.path-common}/${service.name}
service:
  name: job
job:
  repoRefreshJobProperties:
    enabled: false
  deleted-node-cleanup:
    # 已删除节点保留天数
    deletedNodeReserveDays: 14
