spring:
  application:
    name: ${service.name}
    desc: Cocoapods Service
  cloud:
    stream:
      function:
        definition: artifactEvent
      bindings:
        artifactEvent-in-0:
          group: cocoapods
          destination: artifactEvent
          binder: pulsar

server:
  port: __BK_REPO_COCOAPODS_PORT__
logging:
  path: ${logging.path-common}/${service.name}
service:
  name: cocoapods
cocoapods:
  domain: ${cluster.self.url}/cocoapods
  gitPath: ${storage.filesystem.path}/cocoapods/git
