spring:
  application:
    name: ${service.prefix}${service.name}${service.suffix}
    desc: ScannerExecutor Service
server:
  port: __BK_REPO_SCANNER_EXECUTOR_PORT__
logging:
  path: ${logging.path-common}/${service.name}
service:
  name: scannerexecutor

scanner:
  executor:
    work-dir: __BK_REPO_SCANNER_EXECUTOR_WORK_DIR__
    at-least-free-mem-percent: __BK_REPO_SCANNER_EXECUTOR_AT_LEAST_FREE_MEM_PERCENT__
    at-least-usable-disk-space-percent: __BK_REPO_SCANNER_EXECUTOR_AT_LEAST_USABLE_DISK_SPACE_PERCENT__
    docker:
      enabled: __BK_REPO_SCANNER_EXECUTOR_DOCKER_ENABLED__
      host: __BK_REPO_SCANNER_EXECUTOR_DOCKER_HOST__
      version: __BK_REPO_SCANNER_EXECUTOR_DOCKER_VERSION__
      connect-timeout: __BK_REPO_SCANNER_EXECUTOR_DOCKER_CONNECT_TIMEOUT__
      read-timeout: __BK_REPO_SCANNER_EXECUTOR_DOCKER_READ_TIMEOUT__
