spring:
  application:
    name: ${service.prefix}${service.name}${service.suffix}
    desc: Job Service
server:
  port: __BK_REPO_JOB_PORT__
logging:
  path: ${logging.path-common}/${service.name}
service:
  name: job
