# Common config Template 重复的通用的配置抽离在到

spring:
  profiles:
    active: __CPACK_PROFILES_ACTIVE__
  application:
    version: 4.0.0
  cloud:
    consul:
      discovery:
        tags: __CPACK_CONSUL_TAG__
        health-check-path: /management/health
        heartbeat:
          enabled: true
        query-passing: true
        preferIpAddress: true
      port: __CPACK_CONSUL_PORT__
  data:
    mongodb:
      socket-keep-alive: true
      max-connection-idle-time: 60000
      autoConnectRetry: true
      socketTimeout: 1500
      ### 单机情况下关闭事物，否则报错
      transaction:
        enabled: false
      uri: mongodb://__CPACK_MONGODB_USER__:__CPACK_MONGODB_PASSWORD__@__CPACK_MONGODB_ADDR__/__CPACK_MONGODB_DB_NAME__?maxPoolSize=50&replicaSet=rs0&slaveOk=true&safe=true&w=__MONGODB_RES__&wtimeoutMS=2000

feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 600000
        readTimeout: 600000
        logger-level: basic
  compression:
    request:
      enabled: true
    response:
      enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          semaphore:
            maxConcurrentRequests: 100
          thread:
            timeoutInMilliseconds: 600000

ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 30000

swagger:
  enabled: true

logging:
  config: classpath:logback-config.xml
  path-common: __CPACK_LOGS_DIR__

storage:
  type: filesystem
  filesystem:
    path: __CPACK_FILE_PATH__
  cache:
    enabled: false
    path: /data/cpack/repo/filesystem/cached
    expireHours: 12

security:
  # HTTP认证相关配置
  auth:
    # 默认开启
    enabled: true
    # jwt认证相关配置
    jwt:
      # 默认值
      secretKey: secret@key
      # spring Duration配置格式，可以带时间单位，为0表示永不过期，默认为0
      expiration: 0
  # 微服务认证相关配置
  service:
    # 默认开始
    enabled: false
    # 默认值
    secretKey: secret@key

service:
  suffix: "__CPACK_SERVICE_SUFFIX__"
  prefix: "__CPACK_SERVICE_PREFIX__"

# 许可需要的配置  
service-suffix: "-devops"

# 自身节点信息配置
cluster:
  self:
    name: __CPACK_CLUSTER_SELF_NAME__
    url: __BK_HTTP_SCHEMA__://__CPACK_CLUSTER_SELF_DOMAIN__
    username: __CPACK_CLUSTER_SELF_USERNAME__
    password: __CPACK_CLUSTER_SELF_PASSWORD__
  role: __CPACK_ROLE_TYPE__
  center:
    name: __CPACK_CLUSTER_CENTER_NAME__
    url: __BK_HTTP_SCHEMA__://__CPACK_CLUSTER_CENTER_DOMAIN__
    username: __CPACK_CLUSTER_CENTER_USERNAME__
    password: __CPACK_CLUSTER_CENTER_PASSWORD__

bk:
  paas:
    host: __BK_PAAS_PUBLIC_URL__
    version: "__BK_PAAS_VERSION__"

esb:
  code: __BK_CI_APP_CODE__
  secret: __BK_CI_APP_TOKEN__

# 需要限制许可人数的时候
devopsGateway:
  host: __BK_CI_PUBLIC_URL__

# canway certificate
license:
  auth:
    host: __BK_HTTP_SCHEMA__://__CW_LICENSE_HOST__:__CW_LICENSE_PORT__
devops:
  bkHost: __BK_HTTP_SCHEMA__://__BK_PAAS_FQDN__
  appCode: __APP_CODE__
  appSecret: __APP_TOKEN__
  devopsHost: __BK_HTTP_SCHEMA__://__BK_CI_FQDN__
  bkrepoHost: __BK_HTTP_SCHEMA__://__BK_REPO_FQDN__
