# Common config Template 重复的通用的配置抽离在到

spring:
  profiles:
    active: __CPACK_PROFILES_ACTIVE__
  application:
    version: 4.0.0
  cloud:
    consul:
      discovery:
        tags: __CPACK_CONSUL_TAG__
        health-check-path: /management/health
        heartbeat:
          enabled: true
        query-passing: true
        preferIpAddress: true
      port: __CPACK_CONSUL_PORT__
    stream:
      binders:
        noop:
          type: noop
        file:
          type: file
        pulsar:
          type: pulsar
          environment:
            spring:
              pulsar:
                serviceUrl: __PULSAR_SERVICE_URL__:__PULSAR_SERVICE_PORT__
                tokenAuthValue: __PULSAR_AUTH_JWT_TOKEN__
                tenant: __PULSAR_TENANT__
                namespace: __PULSAR_NAMESPACE__
      function:
        autodetect: false
      default-binder: noop
  data:
    mongodb:
      socket-keep-alive: true
      max-connection-idle-time: 60000
      autoConnectRetry: true
      socketTimeout: 1500
      ### 单机情况下关闭事务，否则报错
      transaction:
        enabled: false
      uri: mongodb://__CPACK_MONGODB_USER__:__CPACK_MONGODB_PASSWORD__@__CPACK_MONGODB_ADDR__/__CPACK_MONGODB_DB_NAME__?maxPoolSize=50&replicaSet=rs
  redis:
    host: __CPACK_REDIS_HOST__
    port: __CPACK_REDIS_PORT__
    password: __CPACK_REDIS_PASSWORD__
    timeout: 900

feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 600000
        readTimeout: 600000
        logger-level: basic
  compression:
    request:
      enabled: true
    response:
      enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          semaphore:
            maxConcurrentRequests: 100
          thread:
            timeoutInMilliseconds: 600000

ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 30000

springfox:
  documentation:
    enabled: true

logging:
  config: classpath:logback-config.xml
  path-common: __BK_REPO_LOGS_DIR__

storage:
  type: filesystem
  filesystem:
    path: __CPACK_FILE_PATH_COMMON__/store
  cache:
    enabled: false
    path: __CPACK_FILE_PATH_COMMON__/cached
    expireHours: 12

security:
  # HTTP认证相关配置
  auth:
    # 默认开启
    enabled: true
    # jwt认证相关配置
    jwt:
      # 默认值
      secretKey: secret@key
      # spring Duration配置格式，可以带时间单位，为0表示永不过期，默认为0
      expiration: 0
  crypto:
    rsaAlgorithm: RSA/ECB/PKCS1Padding
    privateKeyStr: "MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAMaoDhrj
                    +Da2tGpawrE8et6vHBjprVj0UiCEza7JVymYTo9gd/pxNJRnbf6NehUL1WP8D6f5e2XZEDNfqXOqyEjPqOKtWIYI6ZLQeQIuAXgyGE5aP3
                    /KVHFnxk+IuzcJtvqTAthfeuVXGel9ATP8hlEyDuCJe7/orBjIVYFk3p+PAgMBAAECgYAGYwLJFIk3YRpdzPszbYlZvXF
                    +z4x2LqyxRPPD6c82lCH6dBSHZbpWBxk/NNc29AFxTHpIYTn5ZUgjDrFI+bWkqxvgqWS/oyfB6rxajIQjTeorsGvt
                    /oumxQA7hvUE2XXLi218RXCURWgz/FZnvNhGhPYUOJWHoPeNlVx3V5mG8QJBAOzP9iSPcw1YJkv6uAgY4MRv1GqPu3NcMif
                    +DQVPOZCNPq7ynSg15Zl3HMpl6jAZNJ/AUXRby3tLhO8WiWr6C8cCQQDWwKbhy4AZ5SDigFIPtk
                    /655Uzprm2JaZSvGkBeOSB9EYCUC1ApKeImrufPZpSj3Ood/fbMyA6cl8Bswl2z335AkBTNa
                    +ToSQYKEUspWhM0BEKdRD6cI65NkgZbVc96lybwkWoS2+VVXrbtdLT+4OSawjmqTj13dtd82c
                    +a3jVsg65AkEAn1kiO0caDZzj8s2OlpQL8rwmDMZ45Lw5FwkwzWPcAsWzsQG3IlFK8uUFtRoryXkiM
                    +6Y3nCoSFYXQxaLPjqmWQJBAI2tn28XAHFcSd0UnS8L6exJuMdjCw4huI5
                    FOeZ0arf5NrWDFoKU30Crw2ozmRBcDvtjDVH9sn8oLC2ObCFItlM="
    publicKeyStr: "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDGqA4a4
                    /g2trRqWsKxPHrerxwY6a1Y9FIghM2uyVcpmE6PYHf6cTSUZ23+jXoVC9Vj/A+n+Xtl2RAzX6lzqshIz6jirViGCOmS0HkCLgF4MhhOWj9
                    /ylRxZ8ZPiLs3Cbb6kwLYX3rlVxnpfQEz/IZRMg7giXu/6KwYyFWBZN6fjwIDAQAB"
  # 微服务认证相关配置
  service:
    # 默认开始
    enabled: true
    # 默认值
    secretKey: secret@key

service:
  suffix: "__CPACK_SERVICE_SUFFIX__"
  prefix: "__CPACK_SERVICE_PREFIX__"

# 自身节点信息配置
cluster:
  self:
    name: __CPACK_CLUSTER_SELF_NAME__
    url: __BK_HTTP_SCHEMA__://__CPACK_CLUSTER_SELF_DOMAIN__
    username: __CPACK_CLUSTER_SELF_USERNAME__
    password: __CPACK_CLUSTER_SELF_PASSWORD__
  role: __CPACK_ROLE_TYPE__
  center:
    name: __CPACK_CLUSTER_CENTER_NAME__
    url: __BK_HTTP_SCHEMA__://__CPACK_CLUSTER_CENTER_DOMAIN__
    username: __CPACK_CLUSTER_CENTER_USERNAME__
    password: __CPACK_CLUSTER_CENTER_PASSWORD__

# cpack 对外服务域名
cpack:
  host: __BK_HTTP_SCHEMA__://__BK_REPO_FQDN__

# 邮箱配置
mail:
  share: true
  host: smtp.exmail.qq.com
  port: 465
  # 邮箱账号，公司环境固定该配置
  username: bkrepo@canway.net
  # 邮箱密码，公司环境固定该配置
  password: e9grYCisezhhaPCp
  protocol: smtps
  smtp:
    auth: true
    starttls:
      enable: true
      required: true

# 集成许可配置
service-suffix: "-devops"

bk:
  ci:
    # license使用的域名
    domain: __CPACK_DOMAIN__
  paas:
    host: http://paas.__CPACK_DOMAIN__
    version: "3.0.0"

# 独立部署模式固定该配置
auth:
  realm: cpack

view:
  domain: __BK_HTTP_SCHEMA__://__BK_REPO_FQDN__
