spring:
  application:
    name: ${service.prefix}${service.name}${service.suffix}
    desc: Replication Service
  cloud:
    stream:
      function:
        definition: artifactEvent
      bindings:
        artifactEvent-in-0:
          group: replication
          destination: event-topic
          binder: noop
server:
  port: __BK_REPO_REPLICATION_PORT__
logging:
  path: ${logging.path-common}/${service.name}
service:
  name: replication
replication:
  domain: ${cluster.self.url}/replication
