spring:
  application:
    name: ${service.prefix}${service.name}${service.suffix}
    desc: Nuget Service
server:
  port: __CPACK_NUGET_PORT__
logging:
  path: ${logging.path-common}/${service.name}
service:
  name: nuget
nuget:
  domain: ${cluster.self.url}/nuget
