spring:
  application:
    name: ${service.name}
    desc: Scanner Service
  # 上报的扫描结果比较大的时候需要配置
  servlet:
    multipart:
      max-request-size: 100MB  
server:
  port: __BK_REPO_SCANNER_PORT__
logging:
  path: ${logging.path-common}/${service.name}
service:
  name: scanner

# 用于存储详细扫描报告
scanner:
  spring:
    data:
      mongodb:
        uri: __BK_REPO_SCANNER_MONGODB_URI__
        transaction:
          enabled: false
