spring:
  application:
    name: ${service.prefix}${service.name}${service.suffix}
    desc: Repository Service
  quartz:
    mongo: true
    startupDelay: 60s
    overwriteExistingJobs: true
    schedulerName: bkrepo-scheduler
server:
  port: __CPACK_REPOSITORY_PORT__
logging:
  path: ${logging.path-common}/${service.name}
service:
  name: repository
