spring:
  application:
    name: ${service.prefix}${service.name}${service.suffix}
    desc: Opdata Service
server:
  port: __BK_REPO_OPDATA_PORT__
logging:
  path: ${logging.path-common}/${service.name}
service:
  name: opdata
