spring:
  application:
    name: ${service.prefix}${service.name}${service.suffix}
    desc: Replication Service
server:
  port: __CPACK_REPLICATION_PORT__
logging:
  path: ${logging.path-common}/${service.name}
service:
  name: replication
replication:
  domain: ${cluster.self.url}/replication
