# Common config Template 重复的通用的配置抽离在到

spring:
  profiles:
    active: __CPACK_PROFILES_ACTIVE__
  application:
    version: 4.0.0
  cloud:
    consul:
      discovery:
        tags: __CPACK_CONSUL_TAG__
        health-check-path: /management/health
        heartbeat:
          enabled: true
        query-passing: true
        preferIpAddress: true
      port: __CPACK_CONSUL_PORT__
  data:
    mongodb:
      socket-keep-alive: true
      max-connection-idle-time: 60000
      autoConnectRetry: true
      socketTimeout: 1500
      ### 单机情况下关闭事物，否则报错
      transaction:
        enabled: false
      uri: mongodb://__CPACK_MONGODB_USER__:__CPACK_MONGODB_PASSWORD__@__CPACK_MONGODB_ADDR__/__CPACK_MONGODB_DB_NAME__?maxPoolSize=50&replicaSet=rs&slaveOk=true&safe=true&w=__MONGODB_RES__&readPreference=secondaryPreferred&wtimeoutMS=2000

feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 600000
        readTimeout: 600000
        logger-level: basic
  compression:
    request:
      enabled: true
    response:
      enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          semaphore:
            maxConcurrentRequests: 100
          thread:
            timeoutInMilliseconds: 600000

ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 30000

swagger:
  enabled: true

logging:
  config: classpath:logback-config.xml
  path-common: __BK_REPO_LOGS_DIR__

storage:
  type: filesystem
  filesystem:
    path: __CPACK_FILE_PATH__
  cache:
    enabled: false
    path: /data/cpack/repo/filesystem/cached
    expireHours: 12

security:
  # HTTP认证相关配置
  auth:
    # 默认开启
    enabled: true
    # jwt认证相关配置
    jwt:
      # 默认值
      secretKey: secret@key
      # spring Duration配置格式，可以带时间单位，为0表示永不过期，默认为0
      expiration: 0
  # 微服务认证相关配置
  service:
    # 默认开始
    enabled: false
    # 默认值
    secretKey: secret@key

service:
  suffix: "__CPACK_SERVICE_SUFFIX__"
  prefix: "__CPACK_SERVICE_PREFIX__"

# 自身节点信息配置
cluster:
  self:
    name: __CPACK_CLUSTER_SELF_NAME__
    url: __BK_HTTP_SCHEMA__://__CPACK_CLUSTER_SELF_DOMAIN__
    username: __CPACK_CLUSTER_SELF_USERNAME__
    password: __CPACK_CLUSTER_SELF_PASSWORD__
  role: __CPACK_ROLE_TYPE__
  center:
    name: __CPACK_CLUSTER_CENTER_NAME__
    url: __BK_HTTP_SCHEMA__://__CPACK_CLUSTER_CENTER_DOMAIN__
    username: __CPACK_CLUSTER_CENTER_USERNAME__
    password: __CPACK_CLUSTER_CENTER_PASSWORD__

# 邮箱配置
mail:
  share: true
  host: smtp.exmail.qq.com
  port: 465
  username: test@canway.net
  password: password
  protocol: smtps
  smtp:
    auth: true
    starttls:
      enable: true
      required: true

# 许可需要的配置
service-suffix: "-devops"

bk:
  paas:
    host: http://paas.canwayrepo.com
    version: "3.0.0"

# 独立部署模式固定该配置
auth:
  realm: cpack
